---

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: create VPC
      amazon.aws.ec2_vpc_net:
        state: present
        name: VPC_Public_Apps
        profile: "{{ profile_aws }}"
        region: "{{ region }}"
        cidr_block: 10.10.0.0/16
        tags:
          Owner: "{{ owner }}"


