---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    var_cidr_vpc : "10.42.0.0/16"
    var_cidr_nginx_ext_az_a : "10.42.10.0/24"
    var_cidr_nginx_ext_az_b : "10.42.11.0/24"
    var_cidr_nginx_int : "10.42.20.0/24"

  tasks:

    - name: create VPC
      amazon.aws.ec2_vpc_net:
        state: present
        name: "{{ owner }}_VPC_Public_Apps"
        profile: "{{ profile_aws }}"
        region: "{{ region }}"
        cidr_block: "{{ var_cidr_vpc }}"
        tags:
          Owner: "{{ owner }}"
          Source: ansible
      tags:
        - create

    - name: delete VPC
      amazon.aws.ec2_vpc_net:
        state: absent
        name: "{{ owner }}_VPC_Public_Zone"
        profile: "{{ profile_aws }}"
        region: "{{ region }}"
        cidr_block: "{{ var_cidr_vpc }}"
      tags:
        - destroy


    - name: Get VPC ID        #needed to create aws resources
      command: aws ec2 describe-vpcs --profile {{ profile_aws }} --region {{ region }} --filter Name=tag:Name,Values={{ owner }}_VPC_Public_Apps --query Vpcs[].VpcId --output text
      register: vpc_id
      tags:
        - create
        - destroy

    - debug: var=vpc_id.stdout
      tags:
        - create
        - destroy


    - name: Create subnet external for NGINX+ in AZ A
      amazon.aws.ec2_vpc_subnet:
        state: present
        profile: "{{ profile_aws }}"
        vpc_id: "{{ vpc_id.stdout }}"
        region: "{{ region }}"
        az: "{{ region }}a"
        cidr: "{{ var_cidr_nginx_ext_az_a }}"
        tags:
          Name: "{{ owner }}_nap_subnet_ext_az_a"
          Owner: "{{ owner }}"
          Source: ansible
      register: nap_subnet_ext_az_a
      tags:
        - create

    - name: Remove subnet external for NGINX+ in AZ A
      amazon.aws.ec2_vpc_subnet:
        state: absent
        profile: "{{ profile_aws }}"
        vpc_id: "{{ vpc_id.stdout }}"
        region: "{{ region }}"
        az: "{{ region }}a"
        cidr: "{{ var_cidr_nginx_ext_az_a }}"
      tags:
        - destroy

    - name: Create subnet external for NGINX+ in AZ B
      amazon.aws.ec2_vpc_subnet:
        state: present
        profile: "{{ profile_aws }}"
        vpc_id: "{{ vpc_id.stdout }}"
        region: "{{ region }}"
        az: "{{ region }}b"
        cidr: "{{ var_cidr_nginx_ext_az_b }}"
        tags:
          Name: "{{ owner }}_nap_subnet_ext_az_b"
          Owner: "{{ owner }}"
          Source: ansible
      register: nap_subnet_ext_az_b
      tags:
        - create

    - name: Remove subnet external for NGINX+ in AZ B
      amazon.aws.ec2_vpc_subnet:
        state: absent
        profile: "{{ profile_aws }}"
        vpc_id: "{{ vpc_id.stdout }}"
        region: "{{ region }}"
        az: "{{ region }}b"
        cidr: "{{ var_cidr_nginx_ext_az_b }}"
      tags:
        - destroy


   - debug: var=nap_subnet_ext_az_a.stdout
      tags:
        - create
        - destroy

    - name: Create nat gateway in AZ A
      amazon.aws.ec2_vpc_nat_gateway:
        state: present
        profile: "{{ profile_aws }}"
        subnet_id: "{{ nap_subnet_ext_az_a[].id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ owner }}_nat_gw_az_a"
          Owner: "{{ owner }}"
          Source: ansible
      register: nat_gateway_az_a
      tags:
        - create

