---

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    var_cidr_vpc : "10.42.0.0/16"

  tasks:

    - name: create VPC
      amazon.aws.ec2_vpc_net:
        state: present
        name: "{{ owner }}_VPC_Public_Apps"
        profile: "{{ profile_aws }}"
        region: "{{ region }}"
        cidr_block: "{{ var_cidr_vpc }}"
        tags:
          Owner: "{{ owner }}"
          Source: ansible
      tags:
        - create

    - name: delete VPC
      amazon.aws.ec2_vpc_net:
        state: absent
        name: "{{ owner }}_VPC_Public_Apps"
        profile: "{{ profile_aws }}"
        region: "{{ region }}"
        cidr_block: "{{ var_cidr_vpc }}"
      tags:
        - destroy


